KCAL-32: Honor call language setting when playing voicemail prompts
2600hz/kazoo-callflow pull request #100
Opened 2022-01-25 18:51 UTC by harenson

2022-02-24 22:26 UTC, lazedo requested changes

2022-02-24 22:26 UTC, lazedo commented on src/module/cf_voicemail.erl
> +                {'ok', _} = kapps_call_command:b_prompt(<<"vm-pin_set">>, kapps_call:language(Call), Call),
this and all others like this. this change doesn't change anything. kapps_call_command:b_prompt/2 uses kapps_call:language

2022-02-25 02:08 UTC, harenson commented on src/module/cf_voicemail.erl
> +                {'ok', _} = kapps_call_command:b_prompt(<<"vm-pin_set">>, kapps_call:language(Call), Call),
The actual intent of those changes is to use `kapps_call_command:b_prompt/3` the version of that function that receives the language you want to play the prompt on and the function does play the prompt on the given language, I tested it myself on my local environment before pushing the changes and it was working as requested. Before those changes it was always using english prompts no matter the configured language because account_override parameter is disabled.

2022-02-25 02:09 UTC, harenson commented on src/module/cf_voicemail.erl
> +                {'ok', _} = kapps_call_command:b_prompt(<<"vm-pin_set">>, kapps_call:language(Call), Call),
https://github.com/2600hz/kazoo-core/blob/master/kazoo_call/src/kapps_call_command.erl#L1475-L1477

2022-03-01 15:42 UTC, lazedo commented on src/module/cf_voicemail.erl
> +                {'ok', _} = kapps_call_command:b_prompt(<<"vm-pin_set">>, kapps_call:language(Call), Call),
https://github.com/2600hz/kazoo-core/blob/master/kazoo_call/src/kapps_call.erl#L1285-L1286

2022-03-01 16:36 UTC, harenson commented on src/module/cf_voicemail.erl
> +                {'ok', _} = kapps_call_command:b_prompt(<<"vm-pin_set">>, kapps_call:language(Call), Call),
I see your point, I am double checking right now. Thank you.

2024-11-22 00:34 UTC, closed without merging