KZOO-252: fixed call not dropping after 3 invalid attempts
2600hz/kazoo-callflow pull request #134
Opened 2022-06-23 18:00 UTC by RefathWadood512

2022-06-23 18:54 UTC, icehess requested changes
You need to format the code, check the CI log.

2022-06-24 12:14 UTC, RefathWadood512 commented
Fixed whitespace and ran` make ci-codechecks `which passed.

2022-06-24 15:48 UTC, jamesaimonetti commented on src/module/cf_voicemail.erl
> +play_message_menu(Promt, Box, Call) ->
Check spelling of Prompt

2022-06-24 15:49 UTC, jamesaimonetti commented on src/module/cf_voicemail.erl
> +    lager:debug("hanging up channel after ~p attempts to get a message action", [?MAX_MESSAGE_MENU_LOOPS]),
put this at info level

2022-06-24 15:50 UTC, jamesaimonetti commented on src/module/cf_voicemail.erl
> +    _ = kapps_call_command:b_prompt(<<"vm-goodbye">>, Call).
call kapps_call_command:hangup/1 next to force the hangup.

2022-06-24 18:18 UTC, merged