[master] - Voicemail envelope prompts customization to enable customized prompt
2600hz/kazoo-callflow pull request #166
Opened 2022-11-09 14:41 UTC by sanjeevie6353

KCAL-46 : Voicemail envelope prompts customization to enable customized prompt

Currently the voicemail envelope will only allow enabling and disabling the envelope to play or ignore the envelope part of the voicemail message announcement.

This new feature will allow to select a specific envelope prompt based on the need. It will be configurable per voicemailbox.

2022-11-09 18:42 UTC, jamesaimonetti requested changes

2022-11-09 18:42 UTC, jamesaimonetti commented on src/module/cf_voicemail.erl
> +  when EnvelopeType =:= <<"caller_and_time">> ->
Use pattern matching in the function clause, no need for the `when` here.

`#mailbox{timezone=Timezone, envelope_type = <<"caller_and_time">>}`

2022-11-10 07:01 UTC, sanjeevie6353 commented on src/module/cf_voicemail.erl
> +  when EnvelopeType =:= <<"caller_and_time">> ->
replaced the `when` with case clause...

2022-11-14 18:54 UTC, sanjeevie6353 commented
Related PRs

https://github.com/2600hz/kazoo-core/pull/523
https://github.com/2600hz/kazoo-crossbar/pull/373
https://github.com/2600hz/kazoo-sounds/pull/28

2022-11-15 06:51 UTC, merged