PS-137 Doorman update
2600hz/kazoo-callflow pull request #216
Opened 2023-06-26 18:10 UTC by pavel-farkas

Updates:

- caller greeting is now configurable
- b-leg is always originated by the same FS node which processes a-leg, this allows to store recorded caller name only locally in /tmp folder and recorded name is always available to b-leg
- doorman menu has been split: callee greeting and caller name playback create one part, which is not interruptible by DTMF, doorman options create second part, where DTMF collection takes place and only this part is repeated when callee selects wrong option
- removed code for cleaning of recorded names, it won't work as intended, cf_doorman would not have right access rights to delete files created by Freeswitch. Instead, /tmp folder of FS nodes is cleaned regularly by cronjob running `tmpwatch`
- caller prompts are now taken from kazoo-sounds, tts is used only for caller greeting when it is configured in doorman document - this allows to override default prerecorded greeting
- callee option "connect and record" has been removed per client request 
- added failover strategy config parameter: what to do if the callee doesn't answer or is busy, default action is **hangup**, alternative is go to **voicemail**
- if no vmbox is configured, doorman will try to find vmbox associated with configured user or owner of configured device
- added config parameter **max_menu_attempts**: how many times to allow the callee to choose from the menu

2023-06-26 19:22 UTC, jamesaimonetti commented on src/module/cf_doorman.erl
> +        {'ok', ?DTMF_HANGUP} ->
If you re-order this clause above the others, you don't need the orelse block anymore, right?

2023-06-27 15:58 UTC, pavel-farkas commented on src/module/cf_doorman.erl
> +        {'ok', ?DTMF_HANGUP} ->
Correct, fixed, thank you.

2023-06-27 23:20 UTC, jamesaimonetti requested changes

2023-06-27 23:20 UTC, jamesaimonetti commented on src/module/cf_doorman.erl
> +      ,{<<"Switch-Nodename">>, kapps_call:switch_nodename(CallerCall)}
As far as I recall, this key does not put the origination leg on the same switch as the caller. Why not use `Existing-Call-ID`?

See https://github.com/2600hz/kazoo-core/blob/master/kazoo_amqp/src/api/kapi_resource.erl#L143

2023-07-04 21:50 UTC, pavel-farkas commented on src/module/cf_doorman.erl
> +      ,{<<"Switch-Nodename">>, kapps_call:switch_nodename(CallerCall)}
Hi James,
yes, I started with `Existing-Call-ID`, but then I realised that everything what is played to callee as 'doorman menu' -prompts, recorded name, options - is also played to caller. Even if those two call legs were not bridged yet. Only solution how to fix it was not using `Existing-Call-ID`. 

Prompts and record playback have parameter to choose call leg for playback, but it was working only for value `both`. As far as I know it should accept also `aleg` and `bleg` values, but result for these two was always silence on both ends.

So I started to look for alternative. I've found your code in `cb_quickcall` module where you set both `Existing-Call-ID` and `Switch-Nodename` together:
https://github.com/2600hz/kazoo-crossbar/blob/master/src/modules/cb_quickcall.erl#L349

But I was mainly inspired by this code:
https://github.com/2600hz/kazoo-core/blob/master/kazoo_amqp/src/api/kapi_resource.erl#L395
where `Switch-Nodename` value is used to create routing key for originate amqp request. Isn't that enough to make sure that request will be processed by required FS node? If not, I will return to `Existing-Call-ID` and try to find another workaround.

Nevertheless, with `Switch-Nodename` set, both call legs were always processed by the same FS node during my tests, so I was convinced that I'm using right parameter.

2023-11-21 17:28 UTC, pavel-farkas commented
Hi @jamesaimonetti,
I'd like to ask for review of updated Doorman code. It now contains all changes that customer required before accepting the final solution. They are using it now for almost two months in production, no complains so far, so I believe it is stable enough. 
Thank you.

2023-11-21 18:00 UTC, jamesaimonetti commented
Yes, thanks for the reminder @pavel-farkas

2023-11-21 23:21 UTC, merged