PISTON-1071: keep many call KVs up to date through cf branches
2600hz/kazoo-callflow pull request #4
Opened 2020-06-01 19:39 UTC by danielfinke

this is a redo under the breakened repos of https://github.com/2600hz/kazoo/pull/6544

- main benefit: capture groups in callflows that are branched to will
  actually work, such as when using cf_callflow or dialing the operator
  in cf_voicemail
- side benefit: tracking KVs stay up to date to understand path thru
  callflows
- props: cf_flow_id, cf_flow_name, cf_flow, cf_capture_group,
  cf_capture_groups, cf_no_match

there's still an open question about the renaming of `Flow` to `FlowDoc` for clarity. 3 options:
1. leave as is in this PR
2. leave as is prior to this PR
3. also update the var names in the cf modules from whatever they are to `FlowDoc` (there are a bunch of different names in them)

2020-06-01 20:49 UTC, lazedo commented
@danielfinke i really don't like the intrusive approach here. this can and will break cf_actions outside of callflow app. we need to consider if we want to take this road.

2020-06-01 21:00 UTC, danielfinke commented
@lazedo so I can get myself up-to-speed, where outside of `callflow` should I be looking for these external cf_actions

2020-06-01 21:15 UTC, lazedo commented
@danielfinke private repos

2020-06-02 00:17 UTC, danielfinke commented
@lazedo any of the ones we already have access to? Or you talking things like konami_pro & ecallmgr_extension

2020-06-02 00:43 UTC, lazedo commented
@danielfinke things that you don't have access to

2020-11-03 00:23 UTC, jamesaimonetti commented
@lazedo anything in particular you see this conflicting with? I don't see any usage of `cf_exe:branch/2` in our private callflow modules which appears to be the main difference in functionality.

I'm inclined to accept unless you have a concrete objection?

2020-11-03 03:00 UTC, lazedo commented on src/cf_route_req.erl
>                 ,{fun kapps_call:set_controller_queue/2, ControllerQ}
repeated

2020-11-03 03:14 UTC, lazedo commented on src/cf_util.erl
> +update_call_on_branch(FlowDoc, NoMatch, Call) ->
`update_call`  seems more appropriate

2020-11-03 03:16 UTC, lazedo commented on src/cf_util.erl
> +update_call_on_branch(FlowDoc, Call) ->
`update_call` seems more appropriate as it may be called not only on branch

2021-02-23 02:49 UTC, danielfinke commented
Rebased to resolve conflicts and addressed review comments

2021-02-23 07:25 UTC, lazedo requested changes
rebase failed

2021-02-23 19:40 UTC, danielfinke commented
@lazedo merge base seems to be correct: https://github.com/2600hz/kazoo-callflow/commits/pr-PISTON-1071-keep-call-kvs-up-to-date
I just don't think I am authorized (or commits authored by me are not authorized) to run the tests

2021-02-23 19:50 UTC, lazedo commented
check the diff, you are deleting a lot of stuff from cf_util

2021-02-23 20:09 UTC, danielfinke commented
@lazedo oh sorry, I'm not sure what happened here. Will correct it.

2021-02-23 20:23 UTC, danielfinke commented
@lazedo fixed that up

2022-04-11 21:44 UTC, jamesaimonetti commented
@lazedo any followup? Looks good to me

2026-04-12 02:45 UTC, closed without merging