HELP-15581: Log when not config menu option was selected after 3 tries
2600hz/kazoo-callflow pull request #7
Opened 2020-07-08 17:06 UTC by harenson

4.3: https://github.com/2600hz/kazoo/pull/6604

2020-08-01 00:39 UTC, icehess requested changes

2020-08-01 00:39 UTC, icehess commented on src/module/cf_voicemail.erl
> +           ) when Loop =< ?MAX_CONFIG_MENU_LOOPS ->
Is there a reason that you're changing this to 3 retries?

2020-08-01 01:03 UTC, harenson commented on src/module/cf_voicemail.erl
> +           ) when Loop =< ?MAX_CONFIG_MENU_LOOPS ->
It starts from 0 (zero) so it loops actually 4 (0-3) times before throwing the error message. I think it was just to make it look the same as the `MAX_INVALID_PIN_LOOPS` macro. Also, it is the same to say `X < 4` than saying `X =< 3` ;)

To be honest I don't recall at the moment why I did it. I can change it back to `Loop < 4` if you want me to do it.

2020-08-01 02:03 UTC, icehess commented on src/module/cf_voicemail.erl
> +           ) when Loop =< ?MAX_CONFIG_MENU_LOOPS ->
It starts at 0?

```
1285:config_menu(Box, Call) ->
1286:    config_menu(Box, Call, 1).
```

2020-08-28 20:31 UTC, harenson commented on src/module/cf_voicemail.erl
> +           ) when Loop =< ?MAX_CONFIG_MENU_LOOPS ->
@icehess You are correct, but it is still looping 3 times as it was before that change. And to answer your question IIRC it was changed to 3 and set to `MAX_CONFIG_MENU_LOOPS` macro just to make its use clear on `config_menu/3 when Loop > ?MAX_CONFIG_MENU_LOOPS` function clause.

2020-08-28 21:50 UTC, merged

2020-08-31 18:02 UTC, harenson commented
Thanks for merging this one. May you also merge the 4.3 backport, please? https://github.com/2600hz/kazoo/pull/6604